#!/usr/bin/env bash
#
# mfpdf - Modifica arquivos pdf
#
# Site      : https://github.com/linuxjeff
# Autor     : Jefferson Santana <computadores.rp@gmail.com>
#
#  -------------------------------------------------------------
#   O programa modifica arquivos pdf para png e txt. O programa
#   é usado para facilitar a alteração de boletos para outros
#   formatos.
#
#   Exemplos:
#
#  -------------------------------------------------------------
#
#
# Histórico:
#
#    v0.0.1 2022-05-23, Jefferson Santana
#       - Versão inicial
#       - Criado cabeçalho
#       - Criado variáveis para arquivo e diretório
#       - Feito a organização das variáveis
#       - Criado variáveis que recolhe o nome do sistema
#    v0.0.2 2022-06-07, Jefferson Santana
#       - Criado a variáveis que verifica se o popller-utils esta instalado
#       - Modificado permissões do arquivo mfpdf para execução
#       - Criado a variáveis que guarda o sistema esperado
#       - Criado a variáveis que guarda a comparação de instalado
#       - Criado o if para testar se o pacote popler-utils esta instalado
#    v0.0.3 2022-06-14, Jefferson Santana
#       - Criado a variável que recebe a versão
#       - Criada variável que recebe o mensagem de ajuda
#
# Licença: MIT.
#

### Variáveis ###
NOMEPADRAODOARQUIVO="documento.pdf"
NOMEDODIRETORIO="~/Downloads"
NOMEDOSO=`egrep '^NAME' /etc/os-release | cut -d "\"" -f 2`
OSESPERADO="Debian GNU/Linux"
VERIFICANDOPOPLLER=`apt search '^poppler-utils' 2>/dev/null | egrep '\[installed\]$' | cut -d ' ' -f 4`
POPLLERINSTALADO="[installed]"
VERSAO=`egrep '^#    v' mfpdf | tail -n 1 | cut -d " " -f 5`
MENSAGEMAJUDA="
Uso: $(basename "$0") [-h|-m|-r|-v]
-h, --help    Mostra esta mensagem e sai
-m, --modify  Modifica o arquivo presente no diretório
-r, --remove  Remove os arquivos presentes no diretório
-v, --version Mostra a versão e sai
"

# O if para o pacote popller-utils
if test "$NOMEDOSO" = "$OSESPERADO"
  then
    if test "$VERIFICANDOPOPLLER" = "$POPLLERINSTALADO"
      then
        echo "Continuando..."
      else
        echo "O programa precisa do pacote popller-utils instalado."
    fi
  else
    echo "Este programa só funciona no Debian até o momento."
fi
