#!/usr/bin/env bash
#
# mfpdf - Modifica arquivos pdf
#
# Site      : https://github.com/linuxjeff
# Autor     : Jefferson Santana <computadores.rp@gmail.com>
#
#  -------------------------------------------------------------
#   O programa modifica arquivos pdf para png e txt. O programa
#   é usado para facilitar a alteração de boletos para outros
#   formatos.
#
#   Exemplos:
#
#  -------------------------------------------------------------
#
#
# Histórico:
#
#    v0.0.1 2022-05-23, Jefferson Santana
#       - Versão inicial
#       - Criado cabeçalho
#       - Criado variáveis para arquivo e diretório
#       - Feito a organização das variáveis
#       - Criado variáveis que recolhe o nome do sistema
#    v0.0.2 2022-06-07, Jefferson Santana
#       - Criado a variáveis que verifica se o popller-utils esta instalado
#
# Licença: MIT.
#

### Variáveis ###
NOMEPADRAODOARQUIVO="documento.pdf"
NOMEDODIRETORIO="~/Downloads"
NOMEDOSO=`egrep '^NAME' /etc/os-release | cut -d "\"" -f 2`
VERIFICANDOPOPLLER=`apt search '^poppler-utils' 2>/dev/null | egrep '\[installed\]$' | cut -d ' ' -f 4`
